import Cabecalho from "./components/Cabecalho";
import Rodape from "./components/Rodape";
import '@/app/globals.css';

export const metadata = {
  title: 'Next.js',
  description: 'Generated by Next.js',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body>
        <Cabecalho/>
          {children}
        <Rodape/>  
      </body>
    </html>
  )
}
